from __future__ import annotations

from pokerengine.pokerengine_core.engine.player import Player, Players
from pokerengine.pokerengine_core.enums.position import PositionEnum

class Positions:
    current: PositionEnum = PositionEnum.NO_POSITION

    def __init__(self, players: Players) -> None: ...
    @property
    def number_alive(self) -> int: ...
    @property
    def player(self) -> Player: ...
    def is_showdown(self) -> bool: ...
    def set_next_current(self) -> None: ...
    def set_next_round_player(self) -> None: ...
