from __future__ import annotations

from typing import List, Tuple

from pokerengine.pokerengine_core.card.cards import Cards
from pokerengine.pokerengine_core.engine.player import Players
from pokerengine.pokerengine_core.evaluation.result import Result

class PotRake01:
    def __init__(self, players: Players) -> None: ...
    @property
    def highest_bet(self) -> int: ...
    @property
    def round_highest_bet(self) -> int: ...
    def pay(self, cards: Cards, flop_dealt: bool) -> List[Tuple[Result, int]]: ...
    def pay_noshowdown(self, flop_dealt: bool) -> List[int]: ...
    def pot(self, flop_dealt: bool) -> int: ...
    def pot_rake(self, flop_dealt: bool) -> int: ...
