from __future__ import annotations

from typing import Final, List

MASK_RANKS_NUMBER: Final[int] = ...
MASK_RANKS: Final[int] = ...
RANKS: Final[int] = ...
SUITS: Final[int] = ...
DECK_SIZE: Final[int] = ...
CARD_INDEX_MIN: Final[int] = ...
CARD_INDEX_MAX: Final[int] = ...
CARDS_STRING: Final[str] = ...
CARD_SET_FULL: Final[int] = ...
BOARD_SIZE: Final[int] = ...
HAND_SIZE: Final[int] = ...
MIN_PLAYERS: Final[int] = ...
MAX_PLAYERS: Final[int] = ...
RAKE01: Final[float] = ...
RAKE_MULTI01: Final[float] = ...
OFFSET_MINOR: Final[int] = ...
OFFSET_MAJOR: Final[int] = ...
OFFSET_TYPE: Final[int] = ...
COMBINATIONS: Final[List[str]] = ...
