from __future__ import annotations

from typing import List, overload

from pokerengine.pokerengine_core.card.card import Card
from pokerengine.pokerengine_core.card.hand import Hand

class Cards:
    @overload
    def __init__(self, board: List[str], hands: List[str]) -> None: ...
    @overload
    def __init__(self, cards: List[Card]) -> None: ...
    def __eq__(self, other: Cards) -> bool: ...
    def __gt__(self, other: Cards) -> bool: ...
    def __lt__(self, other: Cards) -> bool: ...
    def __ne__(self, other: Cards) -> bool: ...
    @property
    def board(self) -> List[Card]: ...
    @property
    def hands(self) -> List[Hand]: ...
    def board_n(self, n: int) -> List[Card]: ...
